In [61]:
import numpy as np
import pandas as pd

In [25]:
a = np.array(['a', 1, "b"])

In [26]:
a

array(['a', '1', 'b'], dtype='<U11')

In [30]:
type(a)

numpy.ndarray

In [29]:
b=np.array([1,2,3])
type(b)

numpy.ndarray

In [31]:
b[2] = 9
print(b)

[1 2 9]


In [32]:
b.shape

(3,)

In [33]:
c = np.full((2,3), "a") #np.full(shape, value)
c

array([['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [37]:
np.zeros((2,3,3)) #creates array with all 0s

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
np.ones((2,3,3))#creates array with all 1s

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
[0]*10 # pythonic

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [51]:
a1 = np.empty((4,)) #empty allocates memory without initializing values,hence we got memory here
a1

array([2.12199579e-314, 6.95187041e-310, 8.51769173e-321, 3.79442416e-321])

In [52]:
a1[0]=2
a1[1] =3
a1

array([2.000e+000, 3.000e+000, 8.518e-321, 3.794e-321])

In [53]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [57]:
#linspace(start, end, number of values to be equally distributed from each other). Generally used in matplotib
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [58]:
np.inf #infinite

inf

In [60]:
None == np.nan 

False

In [65]:
pd.NaT == np.nan

False

In [66]:
pd.NaT == False

False

In [67]:
pd.isna(np.nan)

True

In [68]:
pd.isna(pd.NaT)

True

In [69]:
pd.isna(None)

True

In [70]:
np.isnan(np.nan)

True

In [71]:
np.isnan(pd.NaT) #cant compare numpy with pandas nans

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [72]:
np.isnan(None) #cant compare numpy NaN with Python None

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [74]:
np.sqrt(4) #square root

2.0

In [75]:
np.array([10])/0 # Numpy gives infinite whereas Python gives error

C:\Users\prami\AppData\Local\Temp\ipykernel_4708\1062298245.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([10])/0


array([inf])

In [79]:
np.array([1,2/10,3])/10 #element wise mathematical operation

array([0.1 , 0.02, 0.3 ])

In [146]:
list1 = [1,2,3] 
list1*2 #python duplicates the list

[1, 2, 3, 1, 2, 3]

In [81]:
[ x*2 for x in list1] 

[2, 4, 6]

In [82]:
np.array(list1)*2 #numpy doesnt duplicate but does element wise operation

array([2, 4, 6])

In [83]:
list2 = [5,6,7]


In [89]:
[ x+y for x,y in zip(list1, list2)]

[6, 8, 10]

In [88]:
list1+list2 #python appends on list addition

[1, 2, 3, 5, 6, 7]

In [85]:
np.array(list1)+np.array(list2)  #numpy does element wise operation

array([ 6,  8, 10])

In [90]:
np.log2(10)

3.321928094887362

In [91]:
np.log10(10)

1.0

In [104]:
l1 = [2,3,4]
l2 = [10,11]
l1.append(l2) 

In [105]:
l1

[2, 3, 4, [10, 11]]

In [106]:
l1 = [2,3,4]
l2 = [10,11]
l1.extend(l2) #flattens the list 1 time and appends

In [107]:
l1

[2, 3, 4, 10, 11]

In [147]:
a1 = np.array([2,3,4])
a2 = np.array([[10,11]])
np.append(a1,a2) # by default numpy flattens the list completely (any no of times) and appends

array([ 2,  3,  4, 10, 11])

In [135]:
a3 = np.array([[2,3,4],[10,11,12]])
a4 = np.array([[9,10,11], [10,11,12]])
np.concatenate((a3,a4), axis = 0 ) #row wise

array([[ 2,  3,  4],
       [10, 11, 12],
       [ 9, 10, 11],
       [10, 11, 12]])

In [136]:
np.concatenate((a3,a4), axis = 1 ) #column wise

array([[ 2,  3,  4,  9, 10, 11],
       [10, 11, 12, 10, 11, 12]])

In [109]:
list(a1) #convert numpy array to python lst

[2, 3, 4]

In [116]:
z = np.random.randint(low=0, high=100, size=(2, 3, 4)) #generating random integers for a particular shape
z

array([[[25, 77, 72,  9],
        [20, 80, 69, 79],
        [47, 64, 82, 99]],

       [[88, 49, 29, 19],
        [19, 14, 39, 32],
        [65,  9, 57, 32]]])

In [117]:
z.shape 

(2, 3, 4)

In [112]:
z.reshape(-1) #converts into 1D array

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10])

In [118]:
z.reshape(6,4)

array([[25, 77, 72,  9],
       [20, 80, 69, 79],
       [47, 64, 82, 99],
       [88, 49, 29, 19],
       [19, 14, 39, 32],
       [65,  9, 57, 32]])

In [119]:
z.reshape(4,6)

array([[25, 77, 72,  9, 20, 80],
       [69, 79, 47, 64, 82, 99],
       [88, 49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57, 32]])

In [121]:
z.reshape(-1)

array([25, 77, 72,  9, 20, 80, 69, 79, 47, 64, 82, 99, 88, 49, 29, 19, 19,
       14, 39, 32, 65,  9, 57, 32])

In [122]:
z.reshape((24,))

array([25, 77, 72,  9, 20, 80, 69, 79, 47, 64, 82, 99, 88, 49, 29, 19, 19,
       14, 39, 32, 65,  9, 57, 32])

In [124]:
z

array([[[25, 77, 72,  9],
        [20, 80, 69, 79],
        [47, 64, 82, 99]],

       [[88, 49, 29, 19],
        [19, 14, 39, 32],
        [65,  9, 57, 32]]])

In [123]:
z.flatten() #same as reshape(-1)

array([25, 77, 72,  9, 20, 80, 69, 79, 47, 64, 82, 99, 88, 49, 29, 19, 19,
       14, 39, 32, 65,  9, 57, 32])

In [127]:
[el for el in z.flat]

[25,
 77,
 72,
 9,
 20,
 80,
 69,
 79,
 47,
 64,
 82,
 99,
 88,
 49,
 29,
 19,
 19,
 14,
 39,
 32,
 65,
 9,
 57,
 32]

In [125]:
z.flat

###### np.where

In [141]:
names = ["Alice", "Bob", "Charlie", "David", "Eva", "Fiona", "George", "Hannah", "Ian", "Jane"]
ages = np.random.randint(14, 65, size=10)  # Random ages between 18 and 65
cities = ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"]

# Create DataFrame
df = pd.DataFrame({
    'Name': names,
    'Age': ages,
    'City': np.random.choice(cities, size=10, replace=True)  # Allow cities to repeat
})

df

Name  Age          City
0    Alice   15       Houston
1      Bob   53  Philadelphia
2  Charlie   55      San Jose
3    David   49       Phoenix
4      Eva   52       Phoenix
5    Fiona   25   San Antonio
6   George   60       Phoenix
7   Hannah   32       Phoenix
8      Ian   41       Houston
9     Jane   14       Phoenix

In [142]:
def age_check(a):
    if a>21:
        return "Major"
    else:
        return "Minor"
    

df["class"] = df["Age"].apply(lambda x: age_check(x))
df

Name  Age          City  class
0    Alice   15       Houston  Minor
1      Bob   53  Philadelphia  Major
2  Charlie   55      San Jose  Major
3    David   49       Phoenix  Major
4      Eva   52       Phoenix  Major
5    Fiona   25   San Antonio  Major
6   George   60       Phoenix  Major
7   Hannah   32       Phoenix  Major
8      Ian   41       Houston  Major
9     Jane   14       Phoenix  Minor

In [144]:
df["class2"] = np.where(df["Age"] > 41, "Major", np.where((df["Age"] > 18) & (df["Age"] < 41),"Medium","Minor"))
df

Name  Age          City  class  class2
0    Alice   15       Houston  Minor   Minor
1      Bob   53  Philadelphia  Major   Major
2  Charlie   55      San Jose  Major   Major
3    David   49       Phoenix  Major   Major
4      Eva   52       Phoenix  Major   Major
5    Fiona   25   San Antonio  Major  Medium
6   George   60       Phoenix  Major   Major
7   Hannah   32       Phoenix  Major  Medium
8      Ian   41       Houston  Major   Minor
9     Jane   14       Phoenix  Minor   Minor

In [ ]:
#np.where((condition1), T, np.where((cond2 if not cond1),T , F))